### ISSUE TITLE
Regarding computation of concurrent_io

### ISSUE THREAD

**Issue by yangzhe1990** [python-diamond/Diamond#1]
Hi,

I just found that the computation of concurrent_io is actually util_percentage in its decimal format.

In the following code,
            metrics['concurrent_io'] = (metrics['reads_per_second']
                                        + metrics['writes_per_second']
                                        ) * (metrics['service_time']
                                             / 1000.0)

where (reads_per_second + writes_per_second) = iops = io / time_delta,
service_time = io_milliseconds / io

so concurrent_io is io_milliseconds / time_delta / 1000.0, which is actually util_percentage.

**Comment by bmhatfield** [comment]
Thanks for filing this issue. Due to it's age and inactivity, I am going to close it out. Feel free to submit a PR with proposed changes for further discussion :-)
