### ISSUE TITLE
memory collectors uses wrong property to get actual memory available

### ISSUE THREAD

**Issue by mlowicki** [python-diamond/Diamond#108]
According to documentation (http://pythonhosted.org/psutil/#psutil.virtual_memory) *free* isn't the right property to read amount of available memory - https://github.com/python-diamond/Diamond/blob/master/src/collectors/memory/memory.py#L115

```
free: memory not being used at all (zeroed) that is readily available; note that this doesn’t reflect the actual memory available (use ‘available’ instead).
```

**Comment by Nihn** [comment]
+1

**Comment by deejay1** [comment]
I'd rather have both values (eg free and available)

**Comment by mattrobenolt** [comment]
+1 to logging both.

**Comment by Nihn** [comment]
I've added logging both to my pull request
