### ISSUE TITLE
rhel5 make rpm failure - Python 2.4 compatibility

### ISSUE THREAD

**Issue by nariyaz** [python-diamond/Diamond#122]
byte-compiling /var/tmp/diamond-4.0.87-0-buildroot/usr/lib/python2.4/site-packages/diamond/utils/classes.py to classes.pyc
  File "/usr/lib/python2.4/site-packages/diamond/utils/classes.py", line 151
    except (KeyboardInterrupt, SystemExit) as err:
                                            ^
SyntaxError: invalid syntax

In Python 2.5 and earlier, use the comma version, since as isn't supported.

**Comment by mattrobenolt** [comment]
@kormoc Is there a reason for us to continue supporting python 2.4? That's super old at this point.
