### ISSUE TITLE
DatadogHandler - throwing AttributeError: 'DatadogHandler' object has no attribute 'queue' exception

### ISSUE THREAD

**Issue by SwanJumelle** [python-diamond/Diamond#133]
I've done a debian installation.
I try to use the DatadogHandler by adding `handlers = diamond.handler.datadog.DatadogHandler` to my `/etc/diamond/diamond.conf` I get the following exception (found in `/var/log/diamond/diamond.log`);

```
[2015-03-19 16:57:40,560] [MainThread] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/diamond/handler/Handler.py", line 72, in _process
    self.process(metric)
  File "/usr/lib/pymodules/python2.7/diamond/handler/datadog.py", line 83, in process
    self.queue.append(metric)
AttributeError: 'DatadogHandler' object has no attribute 'queue'
```

**Comment by SwanJumelle** [comment]
The solution is to do ```pip install dogapi``` first

**Comment by josegonzalez** [comment]
Diamond currently logs `Failed to load dogapi module` if the module is not installed. We may not install specific dependencies for downstream collectors/handlers, and you should check on each to be sure you have the correct deps setup.
