### ISSUE TITLE
Datadog - wrong timestamp send

### ISSUE THREAD

**Issue by SwanJumelle** [python-diamond/Diamond#136]
Here is the log from diamond.log

`[2015-03-20 17:11:37,573] [MainThread] Sending.. topic[rax.iostat.xvda.write_requests_merged_per_second], value[2], timestamp[1426866011]`

the time when the data is send is `17:11:37`. But the timestamp value is at `16:40:11`

**Comment by josegonzalez** [comment]
This might be a problem with your ntp setup. I've seen similar issues on my own systems when there is significant drift and ntp/cron are acting up.
