### ISSUE TITLE
Docker Containers

### ISSUE THREAD

**Issue by lesaux** [python-diamond/Diamond#138]
Hello, I've created a "DockerContainersCollector" at https://github.com/lesaux/diamond-DockerContainerCollector which leverages docker-py to gather container metrics.
Would there be some interests of having this included in Diamond?
If so I could work on cleaning it up, adding a few config parameters and creating tests.

**Comment by mzupan** [comment]
:+1:

**Comment by mrh666** [comment]
lesaux, it'll be great!!
