### ISSUE TITLE
load collector config

### ISSUE THREAD

**Issue by fmargelidon** [python-diamond/Diamond#140]
I recently install Diamond to send metrics to statsD. All CPU, Memory, Network... metrics works except ProcessResourcesCollector.

I don't know why but it seems ProcessResourcesCollector does not load my ProcessResourcesCollector.conf.

In file /etc/diamond/diamond.conf, I have :
collectors_config_path = /etc/diamond/collectors/
[[ProcessResourcesCollector]]
enabled = True

In file /etc/diamond/collectors/ProcessResourcesCollector.conf :
enabled=True
unit=kB
cpu_interval=0.1
[process]
[[diamond]]
selfmon=True

And when I check config status after restart Diamond service it does not appear any process or unit in kB.

diamond-setup --print -C ProcessResourcesCollector
ProcessResourcesCollector {'path_suffix': '', 'ttl_multiplier': 2, 'measure_collector_time': False, 'byte_unit': ['byte'], 'instance_prefix': 'instances', 'interval': '10', 'enabled': True, 'metrics_whitelist': None, 'metrics_blacklist': None, 'path_prefix': '', 'path': 'process', 'unit': 'B', 'hostname_method': 'smart', 'process': {}}

And I have a questions also to know how collect metrics for all process running on a server ?

Thanks in advance

**Comment by DStape** [comment]
Hello @fmargelidon, we're trying to prune the backlog of open issues that have accumulated over the years to make maintaining this project easier to maintain going forward. Given that this was opened almost 3 years ago now, we're going to close this issue. However, if you're still hitting the same problems then please just open a new issue and we'll be happy to help, thanks.

@josegonzalez, can we close this please?
