### ISSUE TITLE
Add Collector for inode Usage

### ISSUE THREAD

**Issue by eMerzh** [python-diamond/Diamond#141]
Hi, 

I think it does not exists yet, so here is a little request, 

is it possible to have a collector to monitor Inode usage  ..like the result of a df -i ....

i got a server that crashed today because of that ...

Thanks a lot :)

**Comment by mzupan** [comment]
It is given in the diskspace collector

https://github.com/python-diamond/Diamond/blob/master/src/collectors/diskspace/diskspace.py#L213
