### ISSUE TITLE
PortStat - Counter not available in 2.6

### ISSUE THREAD

**Issue by Goggin** [python-diamond/Diamond#143]
`from collections import Counter` from [here](https://github.com/python-diamond/Diamond/blob/master/src/collectors/portstat/portstat.py#L10) does not work in python 2.6 as it was implemented in 2.7

A backported version of Counter can be located [here](http://code.activestate.com/recipes/576611-counter-class/).  It might be good to include this somewhere in the project as a fallback in case the collections.Counter can't be loaded.

**Comment by thpham** [comment]
+ 1 , I got the same problem

**Comment by mattrobenolt** [comment]
Yeah, I'll fix.

**Comment by mattrobenolt** [comment]
I'm just going to remove the dependency on `Counter` entirely since it's not really being utilized. It's doing something that a simple dict can do instead.

**Comment by mattrobenolt** [comment]
`defaultdict` has existed since python 2.4, and in this case, completely identical in functionality.
