### ISSUE TITLE
Installation via Pip overwrites config

### ISSUE THREAD

**Issue by basilfx** [python-diamond/Diamond#144]
I moved this issue from [the old repository](https://github.com/BrightcoveOS/Diamond/issues/779) to here, as it still bugs me.

I prefer to install Diamond via `pip install (-U) diamond`. However, after I do this, my configuration in `/etc/diamond` is overwritten, meaning that I have to re-enable all collectors again.

Is there something I can do to prevent this (apart from making backups)?

(Ubuntu 14.10, system Python 2.7)

**Comment by DStape** [comment]
Hello @basilfx,

We're going to close this issue, simply because it's almost 3 years old. If you or anyone else continues to run into this problem, please feel free to open a new issue, thanks. @josegonzalez
