### ISSUE TITLE
To run a single collector to test and exit doesn't work.

### ISSUE THREAD

**Issue by himanchali** [python-diamond/Diamond#155]
```
    parser.add_option("-r", "--run",
                      dest="collector",
                      default=None,
                      help="run a given collector once and exit")
```

This feature is not working anymore and it executes all enabled collector instead of only running single collector and exit. This part can be seen removed in commit https://github.com/python-diamond/Diamond/commit/1e49cdfd254b8068f292abd867ba337f599962b1#diff-96492ac5a0fe3a4c6b33a1e1ddc0f34b  . 
Any particular reason? Can I send a pull request and add it back ?

**Comment by DStape** [comment]
Hello @himanchali,

As this issue is approaching 3 years old, we're going to close this. If you (or anyone else reading) still have an interest in running a collector once and then exiting, please open a new issue. Thanks. @josegonzalez

**Comment by DStape** [comment]
Some additional thoughts on this...

Collectors run in their own process space, but whenever the scheduler sees that a collector has died (whether or not the collector decided to commit suicide), the scheduler will always bring it back to life.
Therefore, a solution for this problem might be to outside the scope of the diamond code, i.e. start diamond, wait enough time for the collector to run, stop diamond.
