### ISSUE TITLE
Travis build are failing

### ISSUE THREAD

**Issue by janisz** [python-diamond/Diamond#161]
All [builds PR from last 4 days](https://travis-ci.org/python-diamond/Diamond/pull_requests) are failing for same reason.

    No handlers could be found for logger "bernhard"

**Comment by mattrobenolt** [comment]
I see. The build is broken, but that's not the reason. That's just normal stdout stuff.

It's definitely broken on 2.6 because of #143.

The other failures look like an updated pymongo with a different API? Investigating.
