### ISSUE TITLE
Can we get a new pip package? (4.0.41 is over 3 months old)

### ISSUE THREAD

**Issue by joel-airspring** [python-diamond/Diamond#168]
I installed the latest build from pip (4.0.41).

It contains a bug that is fixed in latest master.  This is the commit:  023895b5bea4295e738056e398515e8e273a97b1

Could a new pip package be pushed?   Current pip is over 3 months old.

Thanks!

*********************************************************************

Also, pip 4.0.41 has a packaging bug of some kind.  It contains this file:

/etc/diamond/collectors/CPUCollector - test2.conf

This stray file with spaces in the name is present in addition to the normal CPUCollector.conf file.

**Comment by justin8** [comment]
+1

Several issues have been fixed but are unavailable without installing from git.

**Comment by Investocat** [comment]
Did https://github.com/python-diamond/Diamond/issues/181 address this?

**Comment by joel-airspring** [comment]
#181 would, but it's not closed, so I'm assuming that the process is not finalized.  It's hard to tell what's going on in #181.  Last comment is a guy saying "Hi guys, any news in the release process? " -- with no response.

I can see that at least one new release has been pushed to pypi since then:  https://pypi.python.org/pypi/diamond/4.0.195

But, again, it's hard to tell what the real release cadence is.
  No announcements on the mailing list:  http://librelist.com/browser/diamond
  Last tag in git is for 4.0:  https://github.com/python-diamond/Diamond/releases
  4.0.195 has been released, but what fixes are in it?
  This issue has remained opened for 6 months without any maintainer responding.
  Etc.

I don't want to sound unappreciative, it's just that it's hard to know when versions are released and what's in them.  I am thankful for the all the hard work that goes into diamond, and I wish you guys the best!
