### ISSUE TITLE
worrying about performance issue

### ISSUE THREAD

**Issue by jumping** [python-diamond/Diamond#176]
I am not sure whether the Diamond has performance issue, there are many processes are running on a server:

![image](https://cloud.githubusercontent.com/assets/255390/7486027/fefe6ac4-f3d0-11e4-9fc0-4f4d44f0c766.png)

Diamond version 4.0.132

**Comment by mattrobenolt** [comment]
As you can tell by the screen shot, none of them are using a ton of resources. This is because diamond forks itself to run collectors in their own process and not block each other.

Is this causing an issue for you somehow? We run this in production at quite a large scale, and diamond is rarely an issue.

**Comment by jaingaurav** [comment]
@mattrobenolt This is actually a bit of a problem for our user case since we have more than 30 collectors running resulting in more than half a gig of memory being used by diamond.

**Comment by mattrobenolt** [comment]
Yeah, that's fair. It'd be worth being able to limit the amount of concurrency. We run tons of collectors as well, but we have tons of memory on each machine, so never noticed. If each process is 20m, that's 600m for all collectors if they're all running concurrently, so that's not great, I suppose.

Either way, I don't have much context about this area of the code that manages all of this. @kormoc added it a while back.

I can look and see if it'd be relatively easy to limit the amount of concurrency and effectively use a semaphore, but don't count on this being done soon. I don't have much time to do that unfortunately.

**Comment by jaingaurav** [comment]
Limiting concurrency would definitely help. Though I'd prefer having tight control on it since the break up of the collectors in different threads ensured that slow collectors would not delay the processing of others. Perhaps some way of grouping collectors in the config file would be useful.

I think a more general concern is why is 20MB being used at all. It seems a bit high for a basic collector to take that much memory.

**Comment by mattrobenolt** [comment]
> I think a more general concern is why is 20MB being used at all. It seems a bit high for a basic collector to take that much memory.

Because python. :smile:

**Comment by jaingaurav** [comment]
Really? I'll do some digging this week, but I feel that we should be able to significantly reduce the resident memory. I have plenty of other processes that take up less memory. Even gunicorn is only half of each diamond collector.

**Comment by mattrobenolt** [comment]
haha, it's definitely possible, but afaik, there weren't many design decisions around keeping the memory footprint low.

**Comment by mzupan** [comment]
Lets just switch the project to Go and be done with it :)

**Comment by jumping** [comment]
I only use the default settings: cpu, load, disk, IO.

**Comment by josegonzalez** [comment]
@mzupan https://github.com/josegonzalez/metricsd

**Comment by Investocat** [comment]
Protip, if you install setproctitle, diamond will tell you what each process is doing

We're not seeing a massive increase in resources on our installs. I believe all forking is copy on write, so the memory claimed is actually much higher then it really is.

    # ps ax | grep -i diamond
     3008 pts/0    S+     0:00 diamond                                                                      
     3010 pts/0    Sl+    0:00 diamond - SyncManager                                                        
     3020 pts/0    S+     0:00 diamond - Handlers                                                           
     3023 pts/0    S+     0:00 diamond - VMStatCollector                                                    
     3026 pts/0    S+     0:00 diamond - CPUCollector                                                       
     3029 pts/0    S+     0:00 diamond - MemoryCollector                                                    
     3032 pts/0    S+     0:00 diamond - LoadAverageCollector                                               
     3035 pts/0    S+     0:00 diamond - DiskSpaceCollector                                                 
     3038 pts/0    S+     0:00 diamond - DiskUsageCollector                                                 
     3043 pts/1    S+     0:00 grep -i diamond

Top shows ~20m per process

      PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                          
     3008 root      20   0  240m  23m 4180 S  0.0  2.3   0:00.48 diamond                                           
     3035 root      20   0  244m  20m 1804 S  0.0  2.1   0:00.00 diamond - DiskS                                   
     3038 root      20   0  244m  20m 1732 S  0.0  2.1   0:00.00 diamond - DiskU                                   
     3032 root      20   0  244m  20m 1796 S  0.0  2.1   0:00.00 diamond - LoadA                                   
     3029 root      20   0  244m  20m 1772 S  0.0  2.1   0:00.00 diamond - Memor                                   
     3026 root      20   0  244m  20m 1796 S  0.0  2.1   0:00.00 diamond - CPUCo                                   
     3023 root      20   0  244m  20m 1824 S  0.0  2.1   0:00.00 diamond - VMSta                                   
     3020 root      20   0  240m  19m 1208 S  0.0  2.0   0:00.00 diamond - Handl                                   
     3010 root      20   0  705m 9276 1532 S  0.0  0.9   0:00.00 diamond - SyncM     

If we actually extract out the PSS of each process:

    # for pid in `pgrep -f diamond`; do grep Pss /proc/$pid/smaps | awk '{ sum+=$2 } END {print sum}'; done
    6866
    5864
    5346
    5358
    5374
    5297
    5440
    5509
    5470

Which is a much lower 5 megabytes per collector. It appears that 5mb is the minimum used, as even going to 40 collectors, each one still uses about 5 mb.

This is at least much more reasonable then the 20m per collector it claims in top.

**Comment by davidbirdsong** [comment]
I'm just now noticing the 1-1 relationship between collector and diamond process. Is there no better way? I don't want to waste energy worrying about the relatively small footprint of a process, but there's something weird about forking a dedicated process to read from /proc once every 15 seconds or something similarly trivial.

Also, I run diamond on nodes that don't have a ton of memory just like I run it on boxes with 64 and 128G of memory. I'd rather not think about restricting collectors to keep process count low.

**Comment by Investocat** [comment]
Process counts don't matter. Resource usage does. CPU usage with 4.1 is a lot lower then in 3.0. We just need to reduce the memory consumption and it will be better.

**Comment by pbooth** [comment]
Actually I'd disagree and say what matters most is impact, not resource usage. 

Impact as in, if I can run application X with this workload and this latency /throughout characteristics, how is the application affected by the use of diamond, vs collectl, vs ganglia, vs sar, vs tesmquest, vs ...

**Comment by Investocat** [comment]
The forking model is one where the indicated memory usage is well over reported. It's a copy on write model so all the processes share the same common memory pages. Having a bunch of sleeping processes in the CPU queue is a lot nicer on the server then having the old single process wake up multiple times a second just to see if it's time to run something. Generically, the memory requirements of the new style should be similar as to the old style, with the addition of less wasted cpu and a stronger guarantee on collections at the correct times. This is the only thing that allowed us to roll it out on our boxes.

**Comment by AnanthRavi** [comment]
Does it make a difference if I run diamond with a different version of Python? Like is it better if I run it with python 3.3 vs 2.7 vs 2.6?

**Comment by shortdudey123** [comment]
Closing since the origional question was answered
Any further concerns should be brought up in a new issue
