### ISSUE TITLE
InfluxdbHandler raise InfluxDBClientError: 404: 404 page not found

### ISSUE THREAD

**Issue by huoxy** [python-diamond/Diamond#197]
I found this import is the reason:

```
try:
    from influxdb.client import InfluxDBClient
except ImportError:
    InfluxDBClient = None
```

In fact, when influxdb -v == 0.8.x, the correct import should be:

```
from influxdb.influxdb08 import InfluxDBClient
```

ref: https://github.com/influxdb/influxdb-python/issues/135

**Comment by huoxy** [comment]
ref: https://github.com/influxdb/influxdb-python/issues/135

**Comment by shortdudey123** [comment]
Dupe of https://github.com/python-diamond/Diamond/issues/137
