### ISSUE TITLE
NetworkCollector not always collecting stats

### ISSUE THREAD

**Issue by justin8** [python-diamond/Diamond#201]
I'm using diamond on 5 machines currently, and only 2 of them actually report network stats.

I'm not sure how to debug the collector, but the only network configuration difference really is that the 3 that are not working are configured via networkmanager and the other two via netctl.

**Comment by huoxy** [comment]
The default interfaces to collect are: eth, bond, em, p1p
you should add more within your situation

ref: https://github.com/BrightcoveOS/Diamond/wiki/collectors-NetworkCollector

**Comment by justin8** [comment]
Ahh, I hadn't realized that. Thanks.

It might be worth updating it to support interface names under systemd considering almost all majors distros are using it now. (eno/ens/enp/enx/wlan/etc)

Full list of them are here: http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

If I get time I'll try and attach a merge request here sometime soon.

**Comment by justin8** [comment]
Bump. This should be a quick and easy merge, it's mostly a config change.

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/208
