### ISSUE TITLE
memory_docker.py doesn't log errors connecting to docker

### ISSUE THREAD

**Issue by docwhat** [python-diamond/Diamond#205]
I get no errors, even with debug logging, when using the `MemoryDockerCollector`.

However, I figured out that it was having trouble connecting to docker due to a version mis-match:

```
[root@linux-centos6 diamond]# python -c 'import docker; print docker.Client().containers(all=True)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 440, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 126, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.18, server: 1.17)")
```

If that error had shown up as a WARN or ERROR (or even INFO) it would have saved me some time.

BTW: The dependency is actually 'docker-py' not 'docker' at https://github.com/BrightcoveOS/Diamond/blob/master/src/collectors/memory_docker/memory_docker.py#L8

**Comment by DStape** [comment]
@josegonzalez, this issue is > 2.5 years old, so should be closed.

@docwhat, if you still see this problem then please feel free to open a new issue and/or pr if you have a fix, thanks.
