### ISSUE TITLE
Mismatch between docs and behavior of PingCollector

### ISSUE THREAD

**Issue by aboks** [python-diamond/Diamond#218]
Suppose `PingCollector` is configured with

```
target_website = 'www.example.org'
```

The documentation ("We extract out the key after target_ and use it in the graphite node we push.") suggests that the metric sent will be `servers.hostname.ping.website`, but the actual metric sent is `servers.hostname.ping.www_example_org`. I don't know what the intended behavior is (and thus whether the doc or the code is wrong), only that there is a mismatch.

**Comment by josegonzalez** [comment]
It uses the target as the metric name. It wouldn't chomp off the subdomain - `www` - or the tld - `org` - as that would have the possibility of causing overlapping metric collection.

As an example, the following would collide:

```
admin.example.com
example.org
```

Those are obviously two different domains, but by your logic, we'd have them both report to `example`, which is definitely wrong. Instead, we simply replace periods in the key to create the metric name.

Hope that helps.

**Comment by aboks** [comment]
Thank you for looking into this @josegonzalez, but I think you misunderstood the issue. I did not mean to suggest that the implementation should strip the subdomain and TLD, as that would obviously be a bad idea for the reasons you pointed out.

Rather, I see there is a mismatch between the documentation (which suggests that the part of the setting name after `target_` is pushed) and the actual code (which sends the hostname with dots replaced by underscores). So either:
* The desired behavior in my example is to push `www_example_com`. In that case the documentation is incorrect and should be updated to say that the metric is derived entirely from the hostname and the part of the setting name after `target_` has no influence...
* ... or the desired behavior in my example is to push `website` (*not* `example`!), as the documentation says. In that case the implementation is incorrect and should probably be fixed.

**Comment by josegonzalez** [comment]
Ah good catch. Mind digging through the ping collector history to figure out what exactly we originally meant to do here?

**Comment by aboks** [comment]
The current behavior (replacing dots with underscores in the hostname) seems to be there from the initial commit of the `PingCollector` (https://github.com/python-diamond/Diamond/commit/be5b89d753ea90b9fe07d70d768cd72cc2c92492). The remark in the documentation was added in https://github.com/python-diamond/Diamond/commit/d62087af7e05412ce7d1cc0ac7a36d2e5c4fcebe, but did not match the implementation at that time. So it was either misunderstanding of the implementation, wishful thinking, or some change that was planned but forgotten.

In my opinion, it seems to be a good idea to implement what's described in the documentation, as the part after `target_` in the key is otherwise unused anyway. That would be a BC break however.

**Comment by josegonzalez** [comment]
Lets change the docs now and then make the new behavior optional?

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/559
