### ISSUE TITLE
How to add Custom Handler

### ISSUE THREAD

**Issue by nickveenhof** [python-diamond/Diamond#220]
Hi,

I tried adding a custom handler to Diamond but it seems I keep failing to do so.

```
import sys
import datetime
import diamond.handler

from diamond.handler.Handler import Handler
from configobj import Section

try:
    import boto
    import boto.ec2.cloudwatch
    import boto.utils
except ImportError:
    boto = None

class cloudwatchHandler(Handler):
```

and filename is mycustomhandler.
I placed it in   /etc/diamond/handlers/ and I see, due to some debugging, that the file is loaded. However it is not handling it as a module.

```
# Directory to load handler configs from
handlers_config_path = /etc/diamond/handlers/
```

The config in diamond.conf is as such:

```
handlers = diamond.handler.mycustomhandler.cloudwatchHandler
```

Is there anything I am missing here? Can someone make a guide on how to add your custom Handlers?

**Comment by nickveenhof** [comment]
Just to note, if I do the following:

```
ln -s /usr/share/diamond/handlers/acquiacloudwatch.py /usr/lib/pymodules/python2.7/diamond/handler/acquiacloudwatch.py
```

it does work, so it seems it is just not picking it up.

**Comment by Investocat** [comment]
handlers_config_path is only handled for config files, you'll want handlers_path under servers to specify the location of the code

**Comment by nickveenhof** [comment]
Good to know. We'll give it a try.
