### ISSUE TITLE
Debian package always runs as the 'diamond' user

### ISSUE THREAD

**Issue by shaunduncan** [python-diamond/Diamond#221]
I'm not entirely sure if this is a bug or the intended behavior, but I have noticed that the example config file for diamond shows that the run user can be configured: https://github.com/python-diamond/Diamond/blob/master/conf/diamond.conf.example#L12-L14. However, locally I have noticed that the service in /etc/init.d sources /etc/default/diamond, which has the diamond user hardcoded. Is diamond expected to always run as the system 'diamond' user? Just looking for some clarity here.

Thanks!

**Comment by shaunduncan** [comment]
It looks like at least how the upstart job is configured, it forces `--skip-change-user` which makes the user setting in diamond.conf have no action: https://github.com/python-diamond/Diamond/blob/master/debian/diamond.upstart#L28

**Comment by josegonzalez** [comment]
If you want to change the user that debian runs your diamond daemon as, you'll need to update your init/upstart/systemd script. Since that is what invokes the diamond daemon - which then loads the config - it's the correct place to edit for changing who runs the daemon.
