### ISSUE TITLE
Multiple whitelist / blacklist config settings

### ISSUE THREAD

**Issue by ethan-eb** [python-diamond/Diamond#230]
The hadoop collector produces a lot of metrics (I'm going to end up using the cassandra collector as well which is a similar case), and I'd like to filter those with metrics_whitelist. However, that setting only accepts a single regex. I don't think that it will be manageable going forward, there will be too many patterns to combine into a single monstrous regex.

I'm interested in adjusting that so that you can provide multiple regex patterns. For both whitelist and blacklist it could stop as soon as it finds a positive match (and proceed or stop as appropriate) - or continue to the end of the list if no match is found and then proceed or stop.

I am happy to put together a pull request for this, but first wanted to ask if it's something that sounds interesting...

**Comment by ethan-eb** [comment]
One other thing: comparing whitelist / blacklist against the *name* and then setting the path afterwards seems incorrect. Wouldn't you expect to be able to pattern match against the full path?

In any case, changing that behavior seems like it could cause unexpected changes with existing configurations in the wild. I'll submit a pull request, but I haven't decided if I should change that.

Feedback appreciated.

**Comment by shortdudey123** [comment]
Merged #245.
