### ISSUE TITLE
HadoopCollector can't use white/black lists

### ISSUE THREAD

**Issue by ethan-eb** [python-diamond/Diamond#234]
I found that my whitelist configuration was being ignored for HadoopCollector, in reading the code I see that it uses self.publish_metric() instead of self.publish() at the end of it's collect() routine. In other collectors the publish method is called, which filters the white/black lists and then calls publish_metrics. 

It should be possible to switch it to publish() the only complication is the way HadoopCollector is building the metric path.

**Comment by ethan-eb** [comment]
One other thing: comparing whitelist / blacklist against the name and then setting the path afterwards seems incorrect. Wouldn't you expect to be able to pattern match against the full path?

It is too limited in the particular case of Hadoop type metrics. You get (for example) a **name** such as *metricssystem.MetricsSystem* ... the path then gets a variety of metrics appended to that *metricssystem.MetricsSystem.Context* *metricssystem.MetricsSystem.NumActiveSources* *metricssystem.MetricsSystem.PublishNumOps* etc, etc.

In any case, changing the existing behavior seems like it could cause unexpected changes with existing configurations in the wild. 

I'm going to try adding a path_filter method, and then provide a way for a collector to choose the path filter if wanted from it's publish method. Will send a pull request...

**Comment by shortdudey123** [comment]
Merged #245.
