### ISSUE TITLE
Hadoop collector, open read-only if not truncating

### ISSUE THREAD

**Issue by ethan-eb** [python-diamond/Diamond#251]
Currently the hadoop collector always opens hadoop metrics files with `'r+'` ... if the settings have `truncate = False` the file should be open `'r'` only to avoid permissions issues under certain circumstances. There is no reason to make the files writeable to the diamond user if not necessary.

**Comment by josegonzalez** [comment]
Do you have a pull request to fix this?

**Comment by josegonzalez** [comment]
Ah it was merged!
