### ISSUE TITLE
Print a better error message than: "Error occurs when initialize logging"

### ISSUE THREAD

**Issue by nhooey** [python-diamond/Diamond#269]
The error message doesn't really tell the user what's wrong with the Diamond config file.

I got this error:

```
Error occurs when initialize logging: 'file'
No handlers could be found for logger "diamond"
```

But if you print a stacktrace and the full exception type, you get:

```
KeyError: 'file'
```

which is slightly more helpful.

More verbose parsing errors would help even more.

**Comment by DStape** [comment]
Hello @nhooey,

As this is a relatively old issue and there are no associated prs, we're going to close this issue. Please feel free to re-open if this is something you still remain interested in thanks.

@josegonzalez
