### ISSUE TITLE
Postgres password required in diamond config file

### ISSUE THREAD

**Issue by dvarrazzo** [python-diamond/Diamond#271]
The postgres collector has a `postgres` default string for the password connection. This basically forces to override the password by writing it in clear text in the `diamond.conf` file or to use a weak auth mode such as  `trust` in `pg_hba.conf`.

There should be a way to not pass a password to the psycopg2 `connect()` function so that the password can be specified in the `.pgpass` file.

**Comment by jaingaurav** [comment]
@dvarrazzo seems like a reasonable suggestion. Any chance you'd be able to provide a PR? Otherwise you might get luck pining some of the dev who have worked on that collector.

**Comment by bmhatfield** [comment]
Fixed by #332
