### ISSUE TITLE
create RealFree in the memory collector

### ISSUE THREAD

**Issue by lerovitch** [python-diamond/Diamond#291]
Hi,

I would like to see if it has sense to create the metric RealFree as proposed by @Henner in https://github.com/BrightcoveOS/Diamond/issues/353

In our team we setup a Diamond-Graphite-Seyren pipeline, and we need the MemFree error alert, but it is not reliable right now.

I am happy to submit a Merge Request if you find it interesting

**Comment by jaingaurav** [comment]
So I kind of like how the collector only publishes metrics present in `/proc/meminfo`. You should be able to make a Seyren alert that uses a graphite function to compute the RealFree

**Comment by lerovitch** [comment]
thanks for the comment,

I had tried to calculate it at seyren with no luck, but it seems it was possible. 

cheers!
