### ISSUE TITLE
Add multi uri to php-fpm collector

### ISSUE THREAD

**Issue by jindov** [python-diamond/Diamond#292]
Hi all,

I have 3 pools for 3 different sites
pool1 for site1.com with uri status /fpm-status-site1
poo2 for site2.com with uri status /fpm-status-site2
pool3 for site3.com with uri status /fpm-status-site3

I need to monitor all of them but diamond cannot add multi uri to phpfpmcollector.conf so someone has a solution for this issue?Thank you

**Comment by KlavsKlavsen** [comment]
Did you ever find a solution for this?

**Comment by DStape** [comment]
Hello @KlavsKlavsen,

Could you clarify exactly what you're looking to do? Do you want to be able to run multiple instances of the same collector, but each with different config?

**Comment by KlavsKlavsen** [comment]
@DStape As I have multiple phpfpm pools - I would like to collect stats from all of them - and have them under f.ex. php-fpm/$poolname/...

**Comment by shortdudey123** [comment]
See comments in #675 on running multiple instances of a collector.
