### ISSUE TITLE
MesosCollector not loading properly

### ISSUE THREAD

**Issue by alde** [python-diamond/Diamond#298]
Due to the mesos.py conflicting with the mesos python library, the mesos-collector doesn't work as expected.

Workaround: rename mesos.py to meso.py

I found it when I kept getting
`1444659840.74   [MainProcess:27359:ERROR]       Can not find collector MesosCollector`

After adding some debug printing of what was actually being loaded, I saw
`<module 'mesos' (built-in)>`
and not
`<module 'mesos' from '/usr/share/diamond/collectors/mesos/mesos.py'>`
As I was expecting.

**Comment by keis** [comment]
using (imp)[https://docs.python.org/2/library/imp.html] rather than `__import__` should avoid this issue

**Comment by mattrobenolt** [comment]
To be fair, we should really just be using `from __future__ import absolute_import` everywhere to avoid this issue.

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/300
