### ISSUE TITLE
Update PyPi package?

### ISSUE THREAD

**Issue by Krylon360** [python-diamond/Diamond#31]
Would it be possible to cut a release to update the PyPi package? did a pip install diamond yesterday and it installed the BrightCove version.

**Comment by kormoc** [comment]
Okay, 4.0.9 has been pushed and I updated the urls in the PKG INFO file.

**Comment by jaingaurav** [comment]
@kormoc What is the corresponding commit id of 4.0.9? When I look at the github releases tab I only see 4.0

**Comment by kormoc** [comment]
it's the 9th commit after 4.0 was cut. We have an open PR to add the hash to the version string so it's easier to track down. 4.0.14 is 9c773b1085ff7ce9f0b3fbc0a4a8969b251d45cd
