### ISSUE TITLE
Diamond can't be installed via Ansible's pip module

### ISSUE THREAD

**Issue by jotes** [python-diamond/Diamond#323]
Hi,
For purposes of my deployment i had to create an automation script in ansible.
Diamond has been installed via following task:

```
- name: diamond | Install package
  sudo: yes
  pip: name='Diamond'
  sudo: yes
```

I've noticed following error after deploy:
All config files, collectors etc. were installed in strange path: /tmp/src/diamond/src
instead of /etc/diamond,/usr/local/share/diamond etc.
However, if i'll install diamond by hand - everything is all right, files are in their right places.

I suspect that there's some kind of mechanism in setup.py that messes up paths for config files.

**Comment by jaingaurav** [comment]
So I'm not to familiar with what exactly is going on, but I've personally not had a lot of luck with the ansible pip module. As a result I typically use the command module like so:

  - name: Install Diamond
    command: pip install --upgrade git+git://github.com/python-diamond/Diamond.git@HEAD

**Comment by morsik** [comment]
Related to #488?

**Comment by shortdudey123** [comment]
See #488.
