### ISSUE TITLE
CloudWatch handler InstanceID dimension to be configurable.

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [python-diamond/Diamond#328]
CloudWatch doesn't allow to set an alarm based on a custom metric with dimension. Actually it does but only per instance so I need to create a separate alarm for each instance.
Optimally `cloudwatchHandler` could have a configuration allowing to specify which metric should be sent with `InstanceID` dimension, without, or both with and without. The latter option will give the possibility to both set a global alarm on all of instances and view metrics drilled per instance.

**Comment by jantman** [comment]
As far as I know, another suitable solution to this would be the ability to specify a dimension other than `InstanceId` in the metric configuration for this handler, i.e. a custom dimension name and value. Then users could alarm on that custom dimension.

**Comment by jantman** [comment]
@josegonzalez @pwilczynskiclearcode I believe this issue was fixed by 38946f670ab161d89476bd2b3a0c2dfff73f6e02
