### ISSUE TITLE
unbounded metric_queue can lead to memory exhaustion

### ISSUE THREAD

**Issue by jraby** [python-diamond/Diamond#329]
I was tracking down a memory usage issue with the `SyncManager` process tonight.
After a good look at the code, it seems like under the right circumstances  `SyncManager` can eat up all available memory.

The root of the issue is that the `metric_queue`, that is shared by all collectors, is unbounded.
If, for whatever reason,  the handlers are not popping stuff fast enough from that queue, the `SyncManager` process (which owns the queue) will grow until it reaches the system limit (or gets killed by the OOM killer)

We've encountered this issue with a single graphite handler that was configured with a wrong host,  the host was unreachable and every connection attempt would timeout  (and the default graphite timeout is 15 seconds, that doesn't help either).
We had ~10 collectors running and configured to poll every 10s. After a few hours, the `SyncManager` was _huge_  ;-)

I'm wondering what would be the right approach to fix this, or even if one approach could fit all needs.

In my case, I'd rather lose some metrics than have a process eat up all available memory (before it gets killed... we'd lose the stats anyways).

For this we could add a  (configurable?) maximum queue size:
```
--- a/src/diamond/server.py
+++ b/src/diamond/server.py
@@ -58,7 +58,7 @@ class Server(object):
         self.manager = multiprocessing.Manager()
         if setproctitle:
             setproctitle(oldproctitle)
-        self.metric_queue = self.manager.Queue()
+        self.metric_queue = self.manager.Queue(512)

     def run(self):
         """
```

This would allow for transient handler failure and would limit the memory usage for that queue.

Then, what should be done in the `QueueHandler._flush()` method?  should it drop the current metric and log an error on `Queue.Full` exceptions?  Or should it block until there's some room available?

If it blocks, it would stop consuming resources until the handler recovers,  but then I think there's a `SIGALARM` shotgun that will kick in after a few seconds...

Any opinions on all this?

**Comment by jaingaurav** [comment]
So PR #256 might be what you are looking for. I think it's largely ready and just needs a config variable. Given the multiple requests for this, I think I might just merge it and add the config myself.

**Comment by jraby** [comment]
haha I should have looked longer at the PRs before hunting this down...

#256 is a bigger change than what I [tested] but please do merge it if it works :) 

[tested]: https://github.com/datacratic/Diamond/compare/datacratic...datacratic:bounded_metrics_queue

**Comment by jaingaurav** [comment]
PR #256 has been merged
