### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by withnale** [python-diamond/Diamond#337]
Last version was 0.4 a year ago.

Any chance of getting a newer tagged stable version?

**Comment by jaingaurav** [comment]
We are going to start a qualification cycle soon, but in the mean time you can install via pip and git

**Comment by nhooey** [comment]
Can we expect a release soon?

**Comment by josegonzalez** [comment]
If someone wants to go through and make some release notes, I'd be happy to do the pip release, @nhooey :)

**Comment by josegonzalez** [comment]
@jaingaurav do we have a slack channel? I'm on the [hangops slack](http://signup.hangops.com/) as `savant` (also on freenode with that nick). Would like to ernestly discuss packaging this thing, even if our release notes say "Lots of things, read the commit messages".

**Comment by DStape** [comment]
@josegonzalez , this issue (and any others that ask for a new release) should be closed.

(For onlookers, I'm working through the backlog of open issues and prs, once I feel I have a good handle on the current state of things, we can agree on when to make a new release.)
