### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by bakerkj** [python-diamond/Diamond#347]
I've just started using python-diamond.  I've noticed that some of the collectors work poorly because the precision published is defaulted to 0.

ping:
In order for sub-millisecond ping times to not round to zero I tried setting the precision to 4 in PingCollector.  This was mzupan fixed this in https://github.com/python-diamond/Diamond/pull/109.

postfix:
For low load mail servers, the derivative values in PostfixCollector are better represented with a few digits of precision.  I tried setting it to 3.

lmsensors:
Voltages found in CPUs are generally around a few volts.  As such there is no variation if it is set to a precision of 2.  It would be more useful to report at least a few digits of precision on these values.  I've tried setting precision to 2 in LMSensorsCollector.

ntpd:
Many of the values are reported as zero with the current implementation of NtpdCollector.  I think the precision should either be fixed a lot higher, or vary based on the data type being published.  I set delay and jitter to 6, and offset, frequency, max_error, est_error, root_distance, and root_dispersion to 10, and left the rest at 0.

**Comment by jaingaurav** [comment]
Thanks for the feedback @bakerkj. What do you think are the next steps? Would you like to submit a PR with these changes. These changes seem quite reasonable to me.

**Comment by bakerkj** [comment]
@jaingaurav sure... I'll have a look at putting a PR together.
