### ISSUE TITLE
Cannot run a given collector once and exit

### ISSUE THREAD

**Issue by hrchu** [python-diamond/Diamond#355]
Hi, 
I follow the instruction [here](http://diamond.readthedocs.org/en/latest/Getting-Started/Custom-Collectors/)

When I fire diamond -f -l -r full/path/to/ExampleCollector.py, ExampleCollector does not executed. Anything do I missed?

**Comment by bigunyak** [comment]
Yeah, this certainly doesn't work, diamond always loads all collectors from the `collectors_path`. The `--run` option is basically ignored.

**Comment by josegonzalez** [comment]
Duplicate of #155
