### ISSUE TITLE
diamond multiprocessing inherit signal handler

### ISSUE THREAD

**Issue by tantra35** [python-diamond/Diamond#356]
if we have collertor, that will be removed later and make diamond reload(send sigHUP), diamond will remove it pid file

Situation is identical like described here:

https://vimmaniac.com/blog/codejunkie/safe-use-of-unix-signals-with-multiprocessing-module-in-python/

In exception that we must set 

```
signal.signal(signal.SIGINT, signal.SIG_DFL)
signal.signal(signal.SIGTERM, signal.SIG_DFL)
```

**Comment by shortdudey123** [comment]
Fixed by https://github.com/python-diamond/Diamond/pull/198
