### ISSUE TITLE
Unable to Disable DEBUG Log on Diamond

### ISSUE THREAD

**Issue by klank4135** [python-diamond/Diamond#361]
The only way I've found to actually disable (verbose) logging, diamond.conf

[server]
change this 
handlers = diamond.handler.graphite.GraphiteHandler, diamond.handler.archive.ArchiveHandler
to that
handlers = diamond.handler.graphite.GraphiteHandler

A possible way to logging is: log WARN+ERROR for system level diamond process things "WARNING: could not load extra python module libsomething", and ERROR for metrics "ERROR: could not connect to mysql to gather metrics".  but _not_ to log every single metric gathered... that's just way too verbose and not useful, except during debugging

**Comment by adfel70** [comment]
If you are using systemd service, [this](https://github.com/python-diamond/Diamond/pull/464) should fix your problem.

**Comment by shortdudey123** [comment]
Probably solved by https://github.com/python-diamond/Diamond/pull/592
