### ISSUE TITLE
version tag

### ISSUE THREAD

**Issue by steenzout** [python-diamond/Diamond#365]
I just checked pypi.python.org and the latest version there is `v4.0.195`.
I check here in github and the latest tag is `v4.0`.

is there a way for me to know what version tag corresponds to a git commit hash?

**Comment by mwicat** [comment]
@steenzout Probably too late but for anyone in the future:
version is computed from git describe:

```bash
~/work/Diamond$ git show
commit 67cab7af27555a9ea8b439574bbc46a91e8d2399
Merge: b5b1379 4530156
Author: Brian Hatfield <bmhatfield@gmail.com>
Date:   Mon Feb 22 16:08:48 2016 -0500

    Merge pull request #404 from csabiftw/add_docker_stats_collector
    
    Add docker stats collector

~/work/Diamond$ git describe
v4.0-397-g67cab7a
```

Here is the code:
- https://github.com/python-diamond/Diamond/blob/master/setup.py#L91
- https://github.com/python-diamond/Diamond/blob/master/version.sh
- https://github.com/python-diamond/Diamond/blob/master/src/diamond/version.py.tmpl

**Comment by steenzout** [comment]
@mwicat do you think it would be possible to start creating the same tags on github for the versions published on pypi?

**Comment by mwicat** [comment]
@steenzout I think so, but it's more a question to package maintaner ;) @jaingaurav ?

**Comment by steenzout** [comment]
here are a pointer in case you'd like travis-ci to do it for you: https://docs.travis-ci.com/user/deployment/releases/

**Comment by steenzout** [comment]
#421 I've added a possible starting point to this.
when a specific version gets tagged, the debian and rpm package would get built and uploaded to the [github releases page](https://github.com/python-diamond/Diamond/releases).

**Comment by steenzout** [comment]
I see you are using `git describe` but if you use a non-annotated tag it will not run this version number.

A test I made:
```
$ git tag v4237892
$ git describe
v4.0-411-gf8379a7
```

**Comment by steenzout** [comment]
patch here: https://github.com/python-diamond/Diamond/pull/423

**Comment by josegonzalez** [comment]
Patch was merged - with a minor modification to ensure we actually capture shell output - and is in use now. Thanks for the pull request!
