### ISSUE TITLE
Prometheus handler

### ISSUE THREAD

**Issue by meganuke19** [python-diamond/Diamond#384]
Hello.
Do you plan add prometheus handler?

**Comment by johnseekins** [comment]
Since Prometheus is a pull model, and diamond is a push model, it's unlikely that a prometheus handler will be made. It would have to completely re-architect how handlers in diamond work.

**Comment by benley** [comment]
You could potentially use the prometheus graphite_exporter module to relay stats from diamond to prometheus.

**Comment by zoidbergwill** [comment]
Prometheus also has a push gateway which can be used to allow things with the push model as well.
