### ISSUE TITLE
Load averages do not contain scaled versions

### ISSUE THREAD

**Issue by zhuyifei1999** [python-diamond/Diamond#387]
Right now the [load averages are non-scaled](https://github.com/BrightcoveOS/Diamond/wiki/collectors-LoadAverageCollector), which, unless the number of cores is known, is meaningless, as one cannot conclude if a node is "overloaded" without scaled data.

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/451

**Comment by jaingaurav** [comment]
Fix was merged
