### ISSUE TITLE
debian package build failed after README.md was symlinked to docs/index.md

### ISSUE THREAD

**Issue by Slach** [python-diamond/Diamond#397]
commit
https://github.com/python-diamond/Diamond/commit/3bca73cf2323c44f319c577bd418b87c797f6cfe

broke debian build

steps to reproduce
<pre>
mkdir -p -v /opt/diamond
git checkout https://github.com/python-diamond/Diamond.git /opt/diamond
cd /opt/diamond/ 
rm -fv /opt/diamond/build/*.deb 
make deb
</pre>

Errror returned
<pre>
copying LICENSE -> /opt/diamond/build/diamond-4.0.380/debian/diamond/usr/share/diamond
error: can't copy 'README.md': doesn't exist or not a regular file
make: *** [install/diamond] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -v4.0.380 failed
make: *** [builddeb] Error 29
</pre>

**Comment by davidballano** [comment]
I just hit this problem too

**Comment by iurii-polishchuk** [comment]
+1

**Comment by jaingaurav** [comment]
commit 10f9289 should resolve this. I don't believe it's necessary to package README.md
