### ISSUE TITLE
In HBase and Hadoop collectors, filename globbing doesn't work when only one pattern is specified

### ISSUE THREAD

**Issue by atoz3q** [python-diamond/Diamond#407]
In the HBase and Hadoop collectors, if only one globbing pattern for metrics filenames is provided, the loop in `collect()` treats the list of patterns as a single string and attempts to iterate over the string's characters. This results in the collector trying to glob over individual characters instead of the string as a whole, breaking the collectors.

**Comment by qardanaz** [comment]
#408

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/408
