### ISSUE TITLE
Add some functionality to the mail collector

### ISSUE THREAD

**Issue by Lacrymology** [python-diamond/Diamond#41]
This is about the collector I sent in #40 

There's one main thing I'd like to add right now that is the possibility of collecting metrics for more than one domain hosted in the server. The main idea behind the `mailbox_prefix` configuration key was to be able to define more than one instance of the collector, each with a different prefix and path (at least our path to the different domain spools are `/var/mail/vhosts/<domain>/`), but I just realized that's not possible.

So what do you think would be the best way of configuring this to have:
- from `/var/mail/vhosts/example.com` collect metrics with prefix `example_com`
- from `/var/mail/vhosts/example.net` collect metrics with prefix `example.net`
- etc

My first thought was to pass `/var/mail/vhosts/*` as a glob and then automatically add the vhost name as a prefix, but the real distribution inside `/var/mail` depends on the mail server and configuration, the only thing the standard says is that you should have plain text files named `<username>` in the UNIX mailbox format for each user's mailbox. But our server has, besides `/var/mail/vhosts/<domain>`, `/var/mail/vhosts/indexes/`, and in there there's a lot of random imap information (the different users folders, trash, history, etc)

Another posible approach woud be:

```
[[MailCollector]]
spool_path = /var/mail         # this will be published without prefix
[[[example_com]]]
spool_path = /var/mail/vhosts/example.com    # prefix=example_com
[[[example_net]]]
spool_path = /var/mail/vhosts/example.net     # prefix=example_net
```

**Comment by kormoc** [comment]
Well, with the new functionality to run a collector multiple times, wouldn't it be better to just run it one time per domain with a different path and spool_path set per collector?

**Comment by Lacrymology** [comment]
wait, I missed this. Sure it would (it was my original idea)

Can you point me to the right spot?

**Comment by shortdudey123** [comment]
See comments in #675 on running multiple instances of a collector.
