### ISSUE TITLE
NetworkCollector and device names

### ISSUE THREAD

**Issue by khodnev** [python-diamond/Diamond#410]
Hi team.

Can you please make changes to NetworkCollector?
It can take the interface names directly from a file /proc/net/dev.
I do not want every time to make a large number of interface names in the configuration file, and restart diamond, if the interface names are called as well as the name of the VPS. 
This can be controlled in the configuration file. 
For example, if the list of interfaces empty in the config - taken from the file /proc/net/dev, else from a list in config file.
It will also help to automate more user-friendly.

Regards,
Alex

**Comment by morsik** [comment]
AFAIK you don't need to specify exact interface names. My config contains:

```ini
interfaces = eth, bond, em, p1p, eno, enp, ens, enx
```

and it handles almost all possible interfaces (yeah, there can be `team`, `vif` or `tun` for example, but I don't need that).

I got that from `diamond-setup`.

Also, this value is default ([according to source code](https://github.com/python-diamond/Diamond/blob/dd3347748c28ec1491627ffa74f898d3f91980a5/src/collectors/network/network.py#L44) so you don't need to specify that value at all (unless you need to capture `vif`s, `team`s or `tun`s ;) ).

**Comment by khodnev** [comment]
I have up to 100 VPS per server. Network interface for VPS is always the same name of the VPS. 
VPS often migrate, add, delete, stop. At the same time I have to manually make changes to the configuration. Why do I have to further specify the interface names in the config file, if they ever have in the file /proc/net/dev ?

**Comment by morsik** [comment]
> Network interface for VPS is always the same name of the VPS

Do I understand correctly? If you have VPS "web01" you have interface called "web1"?! Or what? I still don't see why you need to change that configuration (anyway, just use some configuration management…).

**Comment by khodnev** [comment]
Yes. That's right. 
I have done so that the name of the VPS interface is always equal to the name of the VPS. Then in the statistics will never mess with the interface names, if they are generated automatically, for example vnet0, vnet1, vnet2. Which interfaces was at VPS veb01 before and after a reboot?

And it is not important!
It is important to take interface names from the /proc/net/dev. 
Then list will always be relevant.

**Comment by morsik** [comment]
Ah… I thought you have those interface naming *inside* VMs. But now I see you're talking about hypervisor. Why not to use [LibvirtKVMCollector](https://diamond.readthedocs.io/en/latest/collectors/LibvirtKVMCollector/) then (if you use KVM)? It's very convinient in your case (and my case, cause I have the same problem) and it collects VMs by UUID or they hostname.

But about your problem… Just put empty string inside `interfaces`. Works for me :D

```ini
interfaces =
```

**Comment by josegonzalez** [comment]
Closing as a workaround was provided by another user. Thanks @morsik !
