### ISSUE TITLE
diamond not starting at boot time

### ISSUE THREAD

**Issue by steenzout** [python-diamond/Diamond#414]
I've just noticed that diamond doesn't start at boot time.
Here is the output of a command that could help:
```
$ sudo update-rc.d -n diamond enable
update-rc.d: warning: /etc/init.d/diamond missing LSB information
update-rc.d: see <http://wiki.debian.org/LSBInitScripts>
 System start/stop links for /etc/init.d/diamond do not exist.
```

- diamond version 3.5.0
- Ubuntu 14.04

The LSB information I can figure out but I was just wondering if you came across this problem before and if (and how) you managed to solve it.

**Comment by redref** [comment]
What's your install method (pypi, package, ...), diamond version, and OS version ?

**Comment by steenzout** [comment]
I can see someone added this https://github.com/python-diamond/Diamond/blob/master/debian/diamond.upstart a couple of weeks ago.

closing the ticket.
