### ISSUE TITLE
RabbitMQCollector: I/O error on closed file

### ISSUE THREAD

**Issue by blaztoff** [python-diamond/Diamond#415]
Using RabbitMQ 3.6.1-1. Getting this error:

**An error occurred collecting from RabbitMQ, I/O operation on closed file**

Not much to go on here to see what it is erring out on. Anyone have this issue?

**Comment by merlijntishauser** [comment]
I updated my rabbitMQ docker image to 3.6.1 and tried to reproduce your error, but I get valid metrics returned. Sorry ;)

**Comment by josegonzalez** [comment]
Closing as no one was able to reproduce and there hasn't been an update in a while.
