### ISSUE TITLE
[MainThread] Queue full, check handlers for delays..

### ISSUE THREAD

**Issue by tuyy123** [python-diamond/Diamond#428]
I want to add very many Collectors.
so I added Collectors(12~ 15 collectors) with batch size = 30

but result.. below Image..

<img width="852" alt="2016-03-11 12 36 56" src="https://cloud.githubusercontent.com/assets/13308314/13692570/fae3609e-e785-11e5-8f7a-7c0c6db4ac09.png">

when i increase batch size to 100, then there was no such error.
do i have to increase batch_size?...

**Comment by redref** [comment]
I assume this message pop after some time (depending on your collectors interval).

What metric_queue_size did you configured ? (Logged in DEBUG at starting) 
Approximatively, how many metrics do you send / minute ?
Do you have multiple handlers ? (which one(s) ?)

Increasing batch_size may help but only if handler can handle it.

**Comment by en90choi** [comment]
we did not specify metric_queue_size in configuration file. 
i checked the log, metric_queue_size was default(16384).
these are collectors in our configuration file.
```
[[CPUCollector]]
enabled = True

[[DiskSpaceCollector]]
enabled = True

[[DiskUsageCollector]]
enabled = True

[[LoadAverageCollector]]
enabled = True

[[MemoryCollector]]
enabled = True

[[VMStatCollector]]
enabled = True

[[MY_CUSTOMIZED_COLLECTOR]]
enabled = True
```
with 2 handlers.(ArchiveHandler and MY_CUSTOMIZED_HANDLER).

* process method
```python
    def process(self, metric):
        """
        Process a metric by sending it to graphite
        """
        # Append the data to the array as a string
        self.metrics.append(str(metric))
        if len(self.metrics) >= self.batch_size:
            self._send()
```
approximatively, MY_CUSTOMIZED_HANDLER send 600 metrics / minute.

**Comment by redref** [comment]
Ok. Some informations missing to make a big picture
  * how many metrics in ? (from collectors) interval ? (default seems to be 300s)
  * is handler (and his backend) handling batch_size efficiently ?

Anyway I think you can increase batch_size safely. From my experience, value between (metrics nb / collection interval / 2) and (metrics nb / collection interval) are ok.

To explain a bit. Diamond pop "collectors" processes whenever "interval" is reached, construct "metrics" objects and send it into a multiprocessing.Queue (FIFO). Max size of this queue is parameter "metric_queue_size".

In parallel, one single process (handling all handlers sequentially - 2 in your case), consume queue (with process method). Process method trigger sending data (also sequentially - not losing data) to backend every 'batch_size" metrics received. 

This message pops when queue is full meaning handlers (process + send) are too slow to handle incoming data - or - you sent something like "metric_queue_size" at same time.

Hope this helps a bit.

**Comment by en90choi** [comment]
thanks a lot.
interval was 10, and handler just refer batch_size in if statement..
i think my handler is too slow.

**Comment by en90choi** [comment]
you can close this. it was fixed. i increased batch_size.
