### ISSUE TITLE
Wrong build RPM on Oracle Linux

### ISSUE THREAD

**Issue by thematt** [python-diamond/Diamond#441]
Using Oracle Linux 7.2
platform.dist()[0] on Oracle Linux returns 'oracle', and the condition 

> if distro in ['centos', 'redhat', 'debian', 'fedora']:

 is not satisfied, therefore rpm-package builds without systemd service file.
Please fix it.

**Comment by josegonzalez** [comment]
Closing as the pull request was merged.
