### ISSUE TITLE
Float values 

### ISSUE THREAD

**Issue by Fullmetal8ender** [python-diamond/Diamond#446]
Hi/ I have a problem with getting float values. I have a metric with value 0.001, but diamond always return 0.0 
To send metric I use self.publish(key, metrics[key], None, 1).
What did I do wrong?

**Comment by iurii-polishchuk** [comment]
You should use
`self.publish(metric_name, metric_value)
`

**Comment by Fullmetal8ender** [comment]
In this case I will receive 0.0 beacause of
if precision == 0:
value = round(float(value))


2016-04-01 18:46 GMT+06:00 Iurii Polishchuk <notifications@github.com>:

**Comment by iurii-polishchuk** [comment]
Yes, you're right. Then try precision=3. https://github.com/python-diamond/Diamond/blob/master/src/diamond/metric.py#L28

**Comment by Fullmetal8ender** [comment]
Thank You!

2016-04-01 19:08 GMT+06:00 Iurii Polishchuk <notifications@github.com>:
