### ISSUE TITLE
Support for nginx+ status endpoint

### ISSUE THREAD

**Issue by travisgroth** [python-diamond/Diamond#475]
The commercial subscription for nginx offers a much more detailed status endpoint and I'd like to get that data into diamond.  I presently have most of the code ready.

The dataset and format is completely different than the normal nginx status info, but the options and testing strategy is pretty similar.  Is there a project preference for...

(a) Adding nginx+ support to the existing nginx collector, either automatically determined or set by a config option and updating tests/documentation

or

(b) Creating an entirely separate nginxplus collector, test cases, and documentation

I can put together a PR for either approach.

**Comment by shortdudey123** [comment]
Option A sounds good to me
You can detect which is which based on the `Content-Type` response header (`application/json`for nginx+  vs `text/html` for nginx)
