### ISSUE TITLE
add Categories to PyPI page

### ISSUE THREAD

**Issue by nickjacobson** [python-diamond/Diamond#486]
The download file is called diamond-4.0.451-py2.py3-none-any.whl so I'm assuming Diamond supports Python 3?

If so, these Categories should be added to https://pypi.python.org/pypi/diamond:
Programming Language :: Python
Programming Language :: Python :: 2
Programming Language :: Python :: 3

**Comment by josegonzalez** [comment]
Closing as a pr has been merged.
