### ISSUE TITLE
pypi-install error

### ISSUE THREAD

**Issue by antimion** [python-diamond/Diamond#492]
Hi all, can't install via pypi, i'am trying change pip version but it didn't help.

pypi-install diamond
Traceback (most recent call last):
  File "/usr/bin/pypi-install", line 142, in <module>
    main()
  File "/usr/bin/pypi-install", line 110, in main
    tarball_fname = get_source_tarball(package_name,verbose=options.verbose)
  File "/usr/bin/pypi-install", line 61, in get_source_tarball
    verbose=verbose)
  File "/usr/bin/pypi-install", line 30, in find_tar_gz
    releases = pypi.package_releases(package_name)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
**xmlrpclib.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Forbidden>**

**Comment by trienism** [comment]
I opened the exact same issue https://github.com/astraw/stdeb/issues/122

**Comment by redref** [comment]
Hi @antimion ,

Is there a line missing with exception message ?

IMO, it's a pypi-install related problem like @trienism said.

**Comment by antimion** [comment]
hi @redref 

> xmlrpclib.ProtocolError: ProtocolError for pypi.python.org/pypi: 403 Forbidden

otput not fully copied from shell. This is full error.

**Comment by redref** [comment]
Now for sure, it's not diamond related.
I think this issue can be closed.

**Comment by trienism** [comment]
@redref before you close the issue, is there any reason not to use pip to install diamond on ubuntu?

> Use pypi-install diamond on Debian/Ubuntu systems with python-stdeb installed to build packages.

**Comment by redref** [comment]
Both use setup.py and setuptools/distutils lib. 

I don't see any differences.

**Comment by trienism** [comment]
Cool, thanks.

**Comment by SteveAyre** [comment]
I've commented on astraw/stdeb#122 as I've identified the offending line in stdeb and have a workaround.

**Comment by josegonzalez** [comment]
Judging by the responses, seems like an issue with your tooling, not with Diamond. Closing, but let us know if there is something we might need to fix on our end.
