### ISSUE TITLE
kafka per topic metrics (kafka >= 0.9)

### ISSUE THREAD

**Issue by adfel70** [python-diamond/Diamond#510]
hello,

the kafkastat collector for some reason supports only splitting 2 optional "=" in each mx4j metric at most.
this prevents getting the topic metrics (per each topic).

the fix is very small:

instead of:  

``` python
elif i > 0:
    key = objectname.split('=')[2]
```

should be something like:  

``` python
elif i > 0:
    key = objectname.split('=')[i+1]
```

this would be very helpful !

**Comment by josegonzalez** [comment]
Can you make a pull request for this issue?

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/378
