### ISSUE TITLE
SNMPRawCollector fails due to unexpected response

### ISSUE THREAD

**Issue by dwagon** [python-diamond/Diamond#519]
Using the SNMPRawCollector fails as the data returned by the SNMPCollector() class pretties up the data in the format: SNMPv2-SMI::enterprises.1.2.3.... instead of 1.3.6.1.4.1.1.2.3...

This causes the collector to complain about unexpected response because it isn't in the format that was requested.

**Comment by jacksu** [comment]
Which file call the function collect_snmp(self, device, host, port, community) in the file snmpinterface.py?

**Comment by dwagon** [comment]
snmpinterface collector isn't involved. This is the snmpraw collector.

**Comment by josegonzalez** [comment]
Closed by #520.
