### ISSUE TITLE
Kafka Mbean with type 'java.lang.Object'

### ISSUE THREAD

**Issue by anshulp25** [python-diamond/Diamond#525]
`kafkastat.py` perfectly handles the mbeans having values type : `double`, `float`, `int` and `long`, but some mbeans ( for eg : `kafka.server:type=ReplicaManager,name=LeaderCount` ) has type `java.lang.Object`, which code ignores and doesn't extract values from it.

Any generic way to overcome this ?

**Comment by josegonzalez** [comment]
Not sure, we'll definitely need a patch for that.

**Comment by shortdudey123** [comment]
Solved by https://github.com/python-diamond/Diamond/pull/378
