### ISSUE TITLE
snmp collector how to run?

### ISSUE THREAD

**Issue by jacksu** [python-diamond/Diamond#529]
Which file call the function collect_snmp(self, device, host, port, community) in the file snmpinterface.py?

**Comment by josegonzalez** [comment]
Based on a code search, seems like it was used for tests and nothing else. Any collector that implements `collect_snmp` seems like it might be broken.

What led you to investigate this method?

**Comment by jacksu** [comment]
https://github.com/python-diamond/Diamond/pull/532/files

**Comment by josegonzalez** [comment]
This should be fixed and will go out in the next release. Thanks for keeping on top of this!
