### ISSUE TITLE
Documentation needed: handler configuration in separate file

### ISSUE THREAD

**Issue by bandesz** [python-diamond/Diamond#533]
I'm trying to configure cloudwatchHandler in /etc/diamond/handlers/cloudwatchHandler.conf but however I'm formatting the config it results in different errors. If I put the same configs in /etc/diamond/diamond.conf it works. Could you show me an example please and also add some documentation for this? Thanks!

**Comment by bandesz** [comment]
Diamond version 4.0.451

**Comment by josegonzalez** [comment]
What errors are you seeing?

**Comment by DStape** [comment]
In https://github.com/python-diamond/Diamond/issues/586 I've described my understanding of the differences when configuring collectors vs handlers, so that could be useful.
