### ISSUE TITLE
PyPi link to documentation needs to be updated

### ISSUE THREAD

**Issue by jaingaurav** [python-diamond/Diamond#54]
On https://pypi.python.org/pypi/diamond/4.0.41 the 'Package Documentation' link points to https://github.com/BrightcoveOS/Diamond/wiki instead of https://github.com/python-diamond/Diamond/wiki

**Comment by josegonzalez** [comment]
@kormoc can you make this change?

**Comment by mattrobenolt** [comment]
I just did this.

```
$ curl pythonhosted.org/diamond/
<html>
<head>
<meta http-equiv="Refresh" content="0; url=https://github.com/python-diamond/Diamond/wiki">
</head>
</html>
```

**Comment by vmuriart** [comment]
There is now an option to `Destroy Documentation` in [Pypi](http://stackoverflow.com/a/41856147/5208670).  Hope this helps.
