### ISSUE TITLE
Support for entry_points?

### ISSUE THREAD

**Issue by shaunduncan** [python-diamond/Diamond#56]
I was looking at the implementation for creating custom collectors and handlers and I was curious if there was any thought or plans to support [entry_points](https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins) rather than inspecting a canonical filesystem location. This approach would make it very easy to make custom/third-party collectors and handlers independently versioned, tested, and installed.

If there is some interest in this, I'd be very happy to help with the effort. Thanks!

**Comment by DStape** [comment]
Hello @shaunduncan,

The link you posted is now out-of-data but I believe http://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins points to the same info.

If you are still interested in this, it would be great if you could send an example.

(@josegonzalez , to get on top of the backlog of open issues, I think this can be closed.)

**Comment by josegonzalez** [comment]
Closing. Please comment if this is still an issue.

**Comment by mattrobenolt** [comment]
I did this a long time ago: https://github.com/python-diamond/Diamond/pull/263
