### ISSUE TITLE
ProcessStatCollector must not calculate derivative of procs_running and procs_blocked

### ISSUE THREAD

**Issue by languitar** [python-diamond/Diamond#575]
`procs_running` and `procs_blocked` represent the current number of processes in the respective state. Therefore, `ProcessStatCollector` must not calculate the derivative of these values to keep them interpretable.

For reference: http://man7.org/linux/man-pages/man5/proc.5.html

**Comment by shortdudey123** [comment]
Looks like this was already fixed.  If not, reopen.
