### ISSUE TITLE
pysupport is deprecated in favour of dh-python

### ISSUE THREAD

**Issue by labeneator** [python-diamond/Diamond#578]
Compiling a debian package on ubuntu 16.04 fails due to the removal of pysupport from the apt repos. We need  to bump the buildtooling to use dh-python.  

As a workaround, I used the provided solution in this [ask ubuntu question]( http://askubuntu.com/questions/766169/why-no-more-python-support-in-16-04)

I'll try to do the port and file a PR

**Comment by labeneator** [comment]
Debian has a migration [wiki document](https://wiki.debian.org/Python/TransitionToDHPython2)

**Comment by shortdudey123** [comment]
See https://github.com/python-diamond/Diamond/pull/531 and https://github.com/python-diamond/Diamond/pull/565

**Comment by shortdudey123** [comment]
Taken care of by #710
