### ISSUE TITLE
Issues with SNMP collection

### ISSUE THREAD

**Issue by shaunduncan** [python-diamond/Diamond#59]
Hello!

I'm working on testing out SNMP data collection and I am running into some issues that are leading me to believe that this feature might be broken. I have a small VM setup using the SNMPRawCollector as follows:

```
[[SNMPRawCollector]]
enabled = True
interval = 10
[[[devices]]]
[[[[localhost]]]]
host = localhost
port = 161
community = public
[[[[[oids]]]]]
<my_oid> = mymetric
```

There are a few behaviors I have noticed that are confusing me:
1. The configuration docs on this collector seem to be out of date and do not show proper config nesting (i.e. the docs show `[devices]` instead of `[[[devices]]]`)
2. When the collector fails to run, it fails silently (perhaps this is just my fault in configuring diamond)
3. When the collector runs, it performs no action. I did a little digging and it seems that a removal of a `get_schedule` method may have been the culprit, but I don't know enough about the project internals to confirm this. Some manual work by adding in a `collect` method that did much of the work that `get_schedule` did seems to actually run the collector.

Really, I'm just curious if what I'm seeing is expected or if there is anyone else who has run into similar issues using SNMP collection.

Thanks!

**Comment by shaunduncan** [comment]
Also, is there a discernible difference between the SNMPCollector and SNMPRawCollector? It's not clear to me from the documentation as to when one would be preferable over the other.

**Comment by krbaker** [comment]
the different levels of nesting depend on where you put the configuration I believe.  If you put it in the main config you need more [] than if you put it in the per-collector config. /etc/diamond/collectors/SNMPRawCollector.conf vs /etc/diamond/diamond.conf

**Comment by DStape** [comment]
Hello @shaunduncan, this issues was opened a while ago, is it still a problem?

(@josegonzalez , to get on top of the backlog of open issues, I think this can be closed.)

**Comment by josegonzalez** [comment]
Cool cool, closing.
