### ISSUE TITLE
MongoDB collector authentication

### ISSUE THREAD

**Issue by rcracel** [python-diamond/Diamond#590]
Currently there is no option to specify the authentication database on the MongoDB collector.

It would be nice to have a way to specify the authentication database in addition to the username and password on the collector's configuration.

**Comment by shortdudey123** [comment]
By default it should auth against the admin db.  Typically you should not store root users for monitoring purposes outside of it.  Is this your use case?

**Comment by rcracel** [comment]
My monitoring user is inside the admin password but authentication - my fix was to change the python script to use the admin database for authentication. This is what I had to change to get it to work:

mongo.py line 234
`
            # try auth
            if user:
                try:
                    conn.admin.authenticate(
                        user, passwd, mechanism=self.config['auth_mechanism'], source='admin')
`

**Comment by shortdudey123** [comment]
Read the pymongo code and confirmed it uses `admin` if source is not specified.  So i presume that means something  is overriding it.  I use the mongodb collector with no changes to the auth code.

**Comment by shortdudey123** [comment]
Mongo and the mongo collector have changed a bit since this was opened.  If this is still a problem with current versions, reopen and include current info and log lines.
