### ISSUE TITLE
Error on systemd restart service detected on Debian/Ubuntu

### ISSUE THREAD

**Issue by sideffect0** [python-diamond/Diamond#640]
On restart ing the service with
`systemctl restart diamond`
The command will fail with error because,
`diamond.service: Start request repeated too quickly.`
with recent version of systemd in ubuntu or debian distros.

**Comment by shortdudey123** [comment]
Can you provide more info? logs? diamond, specific os, and systemd version?

**Comment by shortdudey123** [comment]
Unable to replicate the log line mention with Ubuntu 16.04

**Comment by shortdudey123** [comment]
If this is still an issue, reopen and include more info.
