### ISSUE TITLE
Exceptions in collect() method are buried silently

### ISSUE THREAD

**Issue by jamesmulcahy** [python-diamond/Diamond#65]
I have the log level at DEBUG, but exceptions inside a custom collector's collect() method are not reported anywhere in the log.  This makes it quite hard to track down issues.

**Comment by nielsole** [comment]
collector.py:469:
    try:
                start_time = time.time()

            # Collect Data
            self.collect()
...

            finally:
                # After collector run, invoke a flush
                # method on each handler.
                for handler in self.handlers:
                    handler._flush()

No `except:`? This is bugging me for days now. It would be really cool if it would print a stacktrace and the error message!

**Comment by shaunduncan** [comment]
I ran into this same frustration. I put together a small pull request for it: https://github.com/python-diamond/Diamond/pull/60

**Comment by josegonzalez** [comment]
Closing as there is a PR open.
