### ISSUE TITLE
InfluxdbHandler can not send metric to influxdb v1.2

### ISSUE THREAD

**Issue by jindov** [python-diamond/Diamond#653]
Hi guys,

I set up an influxdb v1.2 then I want to use Diamond to send server's metrics to influxdb but it's error:

 

> [2017-05-26 01:17:12,555] [ERROR] [MainThread:Handlers] Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/diamond/handler/Handler.py", line 74, in _process
>     self.process(metric)
>   File "/usr/lib/python2.7/site-packages/diamond/handler/influxdbHandler.py", line 149, in process
>     self._send()
>   File "/usr/lib/python2.7/site-packages/diamond/handler/influxdbHandler.py", line 180, in _send
>     time_precision=self.time_precision)
>   File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 456, in write_points
>     tags=tags, protocol=protocol)
>   File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 506, in _write_points
>     protocol=protocol
>   File "/usr/lib/python2.7/site-packages/influxdb/client.py", line 292, in write
>     data = make_lines(data, precision).encode('utf-8')
>   File "/usr/lib/python2.7/site-packages/influxdb/line_protocol.py", line 149, in make_lines
>     for field_key, field_value in sorted(iteritems(point['fields'])):
> KeyError: u'fields'

My stack is:
- influxdb v1.2
- Diamond 4.0.809
- influxdb python 4.1.0

diamond.conf
```
handlers = diamond.handler.influxdbHandler.InfluxdbHandler
[[InfluxdbHandler]]
hostname = 192.168.1.100
port = 8086 #8084 for HTTPS
batch_size = 100 # default to 1
cache_size = 1000 # default to 20000
username = root
password = root
database = influxdb
time_precision = s
```

The question is "Does InfluxdbHandler support to send metric to influxdb v1.2 or only v0.9 and prior version?"

Thanks

**Comment by szibis** [comment]
https://github.com/python-diamond/Diamond/pull/504

**Comment by shortdudey123** [comment]
See #137.
