### ISSUE TITLE
Docker-collector in version 4.0.809 crash with error

### ISSUE THREAD

**Issue by MetikovVadim** [python-diamond/Diamond#687]
Hello there!

There is no metrics from Diamond Docker collector. In the log i found only:
[MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 77, in collector_process
    collector._run()
  File "/usr/lib/python2.7/site-packages/diamond/collector.py", line 477, in _run
    self.collect()
  File "/usr/share/diamond/collectors/docker_collector/docker_collector.py", line 66, in collect
    client = docker.Client(version='auto')
AttributeError: 'module' object has no attribute 'Client'

How to fix that?

**Comment by MetikovVadim** [comment]
Resolved by downgrade CentOS, install dockerpy and others.

**Comment by gummeah** [comment]
AFAIK the reason is conflict between docker and docker-py python modules. docker module is the new version of docker-py. New versions of docker-compose, for example, using docker. And Diamond is using docker-py.

**Comment by gummeah** [comment]
#https://github.com/gummeah/Diamond/commit/7317dcad3552635bd29398eade4a8ba5fb7ec3ed
This should fix it, if you want to use new version.
