### ISSUE TITLE
MongoDB collector splits logically atomic metric key components

### ISSUE THREAD

**Issue by demonix** [python-diamond/Diamond#697]
Hi!
There was an issue #547, where @bdelbosc notices, that mongo db metrics contains spaces and fixes that. But at the same time he replaced dashes with dots.
That's strange because a lot of metric names contain dashes and logically they must be written as single element in metric key.
We also have dashes in collection and index names, so writing graphite functions on top of these metrics is hard.

So I think, replacing dashes with dots completly wrong. That's easily fixable, but fixing this is breaking change. What do you think?

**Comment by DStape** [comment]
Hi @demonix,

This problem can be solved by adding a new config option to the MongoDB collector that allows the user to specify what delimiter to use. Is this something you'd be able to provide? Thanks.

**Comment by demonix** [comment]
Hi! 
I'm not a python developer, so I just added proposed functionality, without any test, sorry :(

**Comment by shortdudey123** [comment]
Closed by #706
