### ISSUE TITLE
OpenLDAP - Collector 

### ISSUE THREAD

**Issue by Vandy07** [python-diamond/Diamond#702]
Hello,
 
When i try collect metrics of my openldap,  using OpenLDAP - collector, presents this messages of error:
 
_[2018-03-12 18:23:48,641] [MainThread] Unable to query ldap://<IP>:389: {'info': u'TLS error -5938:Encountered end of file', 'errno': 21, 'desc': u'Connect error'}
[2018-03-12 18:24:08,470] [MainThread] Unable to query ldap://<IP>:389: {'info': u'TLS error -5938:Encountered end of file', 'desc': u'Connect error'}_
 
This can be a issue?
 
Tks!

**Comment by shortdudey123** [comment]
If this ends up being a diamond specific issue, reopen.
