### ISSUE TITLE
Can I send metrics to Diamond directly somehow?

### ISSUE THREAD

**Issue by connexion2000** [python-diamond/Diamond#721]
Hi,
can I send metrics to Diamond directly?

**Comment by trinitronx** [comment]
Why would you want to do that?  Diamond is designed to gather & send metrics to a remote handler.  You probably want something like Graphite, StatsD, etc...

**Comment by shortdudey123** [comment]
Hopefully the above comment answered your question.  If not, reopen.
Closing . . .
