### ISSUE TITLE
delete = False in [[FilesCollector]] config file is delete = 'False', so it is True

### ISSUE THREAD

**Issue by connexion2000** [python-diamond/Diamond#724]
I noticed that any boolean value specified in config file and that is specific to any collector isn't handled correctly. It doesn't use str_to_bool() method nad is always string internally, so it is always True.

**Comment by shortdudey123** [comment]
For the files collector you are correct.  However since the default is a boolean False, as long as you do not specify it in the config, you avoid this.  Feel free to submit a PR if you wish to fix this.

Closing . . .
