### ISSUE TITLE
MongoDBCollector ignores metrics_whitelist?

### ISSUE THREAD

**Issue by UdiBen** [python-diamond/Diamond#732]
Hi,

I'm trying to report mongo stats, and I added this mongodb collector configuration.
(I'm using HostedGraphite and I'm trying to reduce metrics count by using whitelist)

Here's my configuration:

[[MongoDBCollector]]
enabled = True
hosts = localhost:27017
metrics_whitelist = .*mongo.(?:connections|locks).*|.*mongo\\.metrics\\.(?:document|cursor).*|.*mongo\\.databases.*\\.(?:size|totalIndexSize|count)

And now I don't get any metrics...

Any idea why?

**Comment by greggy** [comment]
Now it hasn't config `metrics_whitelist`.

**Comment by shortdudey123** [comment]
I am guessing your reggex is wrong.  Please double check it.  Reopen if it is correct and you still have no metrics reported.   Also include a current config and log output.
