### ISSUE TITLE
Spike after missing data points

### ISSUE THREAD

**Issue by nikhilaii93** [python-diamond/Diamond#753]
I'm using a diamond collector to fetch the num_fds of a machine. At certain times I've observed that the no. of data points become large suddenly and that happens precisely with a period of missing data points. Could It be because the collector is aggregating the missing data points?
Attaching a screenshot of the plot where at all times the value is **149 except at peak when it is 25479**, the missing duration is from 7:47 AM to 10:51 AM (inclusive). Also, **25479/149 = 171** which is exact multiple looks suspicious.
![image](https://user-images.githubusercontent.com/2110767/108506811-67d1ac80-72df-11eb-8280-9ebc1dbcec69.png)

**Comment by shortdudey123** [comment]
Based on the info provided, I would agree that it is aggregating the data points.  As to the reason for the missing data, you do not provide enough info.  Diamond logs might give you a clue.  Re-open if you have further questions.
