### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by PolTorrentTornos** [python-diamond/Diamond#756]
Hi there! 
I'm trying to use diamond but every time I ask for 
diamond or diamond-setup I get:
`diamond
  File "/home/pol/anaconda3/envs/pol36/bin/diamond", line 113
    print "Diamond version %s" % (get_diamond_version())
                             ^
SyntaxError: invalid syntax`
`diamond-setup
  File "/home/pol/anaconda3/envs/pol36/bin/diamond-setup", line 68
    print "Failed to import module: %s. %s" % (
                                          ^
SyntaxError: invalid syntax
`
I installed it with `pip install diamond` in a python 3.6 env. The installed version of diamond is 4.0.515. I did changed the diamond.conf.example to diamond.conf

Help please!

**Comment by mattrobenolt** [comment]
I highly doubt Diamond works on Python 3.6. This hasn't been maintained or updated in quite a while. Last I recall, we were still maintaining python 2.5 and 2.6 support.

**Comment by PolTorrentTornos** [comment]
Hi,
Yes it did work in the end but I had to use the default one from bioconda,
v0.9. I was pretty impressed.

El dv., 16 d’abr. 2021, 18:28, Matt Robenolt ***@***.***> va
escriure:
