### ISSUE TITLE
collect_without_dimension not in latest release

### ISSUE THREAD

**Issue by Jackleberry** [python-diamond/Diamond#758]
I'd like to use the `collect_without_dimension` option when collecting varnish metrics with the cloudwatch handler. I see it in the code base but not in the latest release even though the code was added before the release date. 

```
self.valid_config = ('region', 'collector', 'metric', 'namespace',
                             'name', 'unit', 'collect_by_instance',
                             'collect_without_dimension')
```

https://github.com/python-diamond/Diamond/blob/master/src/diamond/handler/cloudwatch.py#L88

Would it be possible to create a new release that includes these changes?

**Comment by shortdudey123** [comment]
Use #709 to track a new release.
