### ISSUE TITLE
mysql.py is not a good name for a collector

### ISSUE THREAD

**Issue by isotopp** [python-diamond/Diamond#76]
I tried to use the MySQLCollector defined in src/collectors/mysql/mysql.py. 

Diamond has claimed to load this: `Loaded Modules: mysql`, but was not loading the class. For the mysql55.py collector, `Loaded Modules: mysql55` was followed by `Loaded Collector: mysql55.MySQLPerfCollector`, but for the mysql.py, `Loaded Collector: MySQLCollector` never showed. 

That was, because

    [2015-01-22 16:35:09,344] [MainThread] Loaded Collector: mysql55.MySQLPerfCollector
    open("/usr/lib/python2.7/dist-packages/mysql/__init__.py", O_RDONLY) = 4

so the mysql.py file has been shadowed due to include path issues. 

Renaming the collector definition to mysqlcollector.py fixed the issue.

**Comment by isotopp** [comment]
Alternatively, you change the way you load the module in a way that the module search path is more limited. That might be the better option, actually.

**Comment by josegonzalez** [comment]
The way we handle this for redis is by naming it `redisstat`. Can you make a pr renaming it `mysqlstat`?

**Comment by mattrobenolt** [comment]
We just hit this issue with the kafka module as well. :(

**Comment by josegonzalez** [comment]
Mind making a pr for the kafka module?

**Comment by mattrobenolt** [comment]
I'm just going to fix both of these on master. :) One sec.

**Comment by isotopp** [comment]
You will be hitting these again and again, because the actual problem is the module search path. This is what needs to be fixed instead.

**Comment by mattrobenolt** [comment]
@isotopp If you submit a PR, I'll happily take a look. :) In the meantime, what I've done works. But I agree, it's not the ideal solution. We will hit this problem again with other modules.

**Comment by josegonzalez** [comment]
To be honest, I never understood why the collectors weren't all called after the classes they contained (`mysql_collector.py`, `redis_collector.py`). Perhaps we should do that unless @kormoc has any objections?
