### ISSUE TITLE
cloudwatchHandler failed to compare metrics

### ISSUE THREAD

**Issue by choopooly** [python-diamond/Diamond#78]
I'm trying the cloudwatchHandler but for some reason I can't make it work.
The connection with cloudwatch works fine, but during the cloudwatch.process function , metric.getMetricPath() return nothing so the comparison fails without any log message.

```
diamond[13010] DEBUG diamond cloudwatch.process:186 Comparing Collector: [loadavg] with (loadavg) and Metric: [01] with ()
```

Here is my config

``` [handlers]

[[cloudwatchHandler]]
region = us-west-2

[[[LoadAvg01]]]
collector = loadavg
metric = 01
namespace = os
name = Avg01
unit = None

[collectors]

[[default]]
enabled = False
# path_suffix = os

[[LoadAverageCollector]]
enabled = True
```

Also, I probably misinterpreted the config with the namespace, but if I add path_suffix = os to my collectors, the comparison log:

```
Comparing Collector: [loadavg] with (os) and Metric: [01] with ()
```

**Comment by josegonzalez** [comment]
@choopooly Were you able to figure out what was going on?

**Comment by choopooly** [comment]
@josegonzalez unfortunately no.

**Comment by josegonzalez** [comment]
Closing as we haven't seen any other reports and there hasn't been any update to this issue. Its possible that your IAM permissions were incorrect, resulting in null values.
