### ISSUE TITLE
"pip install diamond" failed (CentOS 7, diamond 4.0.41)

### ISSUE THREAD

**Issue by AlexAkulov** [python-diamond/Diamond#79]
Hello,
I can not install Diamond through "pip" in CentOS 7
Installation fails with the error: 
> ...
> error: can't copy 'rpm/systemd/diamond.service': doesn't exist or not a regular file
> ...

File setup.py in package diamond-4.0.41.tar.gz contains:
```python
if distro in ['centos', 'redhat', 'debian', 'fedora']:
            data_files.append(('/etc/init.d',
                               ['bin/init.d/diamond']))
            data_files.append(('/var/log/diamond',
                               ['.keep']))
>>>            if distro_major_version >= '7' and not distro == 'debian':
                data_files.append(('/usr/lib/systemd/system',
                                   ['rpm/systemd/diamond.service']))
            elif distro_major_version >= '6' and not distro == 'debian':
                data_files.append(('/etc/init',
                                   ['rpm/upstart/diamond.conf']))
```
but there is no file "rpm/systemd/diamond.service" in the archive

**Comment by josegonzalez** [comment]
Interesting, the file exists [here](https://github.com/python-diamond/Diamond/blob/master/rpm/systemd/diamond.service).

Is someone familiar with packaging that might be able to figure out whats going on here?

**Comment by docwhat** [comment]
Is there a workaround for this? To, for example, not install the services/init.d stuff? I don't need/want it anyway.

**Comment by docwhat** [comment]
@josegonzalez It exists in git, but not in the tarball...

The tarball being used is here: https://pypi.python.org/pypi/diamond/4.0.41

```
$ tar tvf diamond-4.0.41.tar.gz | grep rpm
drwxr-xr-x  0 kormoc staff       0 Jan  4 22:22 diamond-4.0.41/rpm/
drwxr-xr-x  0 kormoc staff       0 Jan  4 22:22 diamond-4.0.41/rpm/upstart/
-rw-r--r--  0 kormoc staff     297 Jul 31  2012 diamond-4.0.41/rpm/upstart/diamond.conf
```

As you can see, the `rpm/systemd` is missing.

This is because whomever packaged it did it on a non-CentOS 7 system.  The `data_files` variable is incorrectly switching on OS versions in `setup.py`; it should always include those files.  Whether you use them should be based on the OS, not whether they should be packed up.

**Comment by docwhat** [comment]
I tested this in version 4.0.195 and it seems to be fixed now, so this probably can be closed.

**Comment by AlexAkulov** [comment]
Thanks!
