### ISSUE TITLE
Debian package does not create group for diamond user

### ISSUE THREAD

**Issue by shaunduncan** [python-diamond/Diamond#80]
I am not sure if this is intended behavior, but currently creating a debian package and installing creates a 'diamond' user but does not explicitly place that user into a group. I would expect that a group 'diamond' would also be created. I have not looked at either the RHEL/gentoo packaging to see if this is the same behavior. Is not having an explicit group created expected?

Thanks!

**Comment by josegonzalez** [comment]
What user does diamond currently run as?

**Comment by deejay1** [comment]
@josegonzalez according to the package as the diamond user
