### ISSUE TITLE
Allow IAM role authentication for the SQS Collector

### ISSUE THREAD

**Issue by bwbaugh** [python-diamond/Diamond#81]
The [SQS collector](https://github.com/python-diamond/Diamond/blob/master/src/collectors/sqs/sqs.py) should be able to use [IAM role](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) authentication, similar to how the [ELB collector](https://github.com/python-diamond/Diamond/blob/d429c52e9c39a81d7d15adc6b52531a39e621527/src/collectors/elb/elb.py#L156,L159) already allows.

**Comment by josegonzalez** [comment]
@bwbaugh Would you like to make a PR for this feature?
