### ISSUE TITLE
Diamond hemorrhages memory when Graphite server is inaccessible

### ISSUE THREAD

**Issue by jgoldschrafe** [python-diamond/Diamond#84]
I recently ran into a situation on one of my hosts where Diamond 4.0 series was consuming over 3 GB of memory after being unable to connect to Graphite for a couple of hours -- RES in htop appears to grow by 2-3 MB per minute. I'm not sure if this is an issue with unbounded write buffer growth or leaked objects in connection handling, but it presents a serious threat to system stability.

**Comment by jaingaurav** [comment]
What collectors do you have enabled? Would you know which collector is causing this?

**Comment by jgoldschrafe** [comment]
It's occurring on a number of hosts with a number of different collector configurations enabled while the Graphite server is down. There is a direct relationship between the number of metrics collected and the rate of memory increase (i.e. hosts with an HAProxy or MongoDB collector enabled, which publish a lot of metrics, see the memory usage increase significantly faster).

**Comment by shawnbutts** [comment]
Assuming the GraphitePickleHandler is being used, https://github.com/python-diamond/Diamond/pull/94 might take care of this.

**Comment by aferrari-technisys** [comment]
Hi guys, just to confirm that this is a big issue... currently in my case is using 85% of my memory:

[root@SUPV6746 ~]# ps aux | grep diamond
root      1687  0.0 85.6 7555348 6899476 ?     Sl   Apr30  58:15 /usr/bin/python /usr/bin/diamond -p /var/run/diamond.pid

Inclusive after restart... hope some can take care about this...

**Comment by aj-jester** [comment]
I've recently come across this bug as well. Any idea for the fix?

**Comment by jgoldschrafe** [comment]
I've ended up just running Diamond with cgroup confinement on my systems to keep it from taking the whole system down when Graphite backs up.

cgconfig.conf:

    group diamond {
      memory {
        memory.limit_in_bytes = 128M;
      }
    }

I then updated the Upstart config (Ubuntu 14.04) to launch Diamond with:

        exec start-stop-daemon --start --make-pidfile --chuid $DIAMOND_USER --pidfile $DIAMOND_PID --exec /usr/bin/cgexec -- -g memory:diamond $DAEMON --foreground --skip-change-user --skip-fork --skip-pidfile

**Comment by rtoma** [comment]
Are we talking about the graphite.py or the graphitepickle.py handler here?

The graphite.py handler has backlog control. If active it logs warnings to the diamond.log, like:
```
                self.log.warn('GraphiteHandler: Trimming backlog. Removing'
                              + ' oldest %d and keeping newest %d metrics',
```
The graphitepickle.py handler is a subclass of the graphite handler, so it also should emit these warnings.

Anyone with memory issues around that can grep their diamond logging for warnings like this?

**Comment by aj-jester** [comment]
@rtoma I went through the logs for the past week and I don't see the warning. Does that mean backlog control is not enabled? How can we activate the backlog control? or is there a way we can tune it? I'd rather we lose some metrics than crash the entire node :disappointed: 

Thanks.

**Comment by rtoma** [comment]
@aj-jester That 'took too long' warning may be related. When looking in the sourcecode it seems to mean one or more of your collectors could not finish within the set interval.

How often do you run your collectors? Thats set as "interval = " in your /etc/diamond/diamond.conf or /etc/diamond/collectors/*.conf.

Maybe you run with more collectors than your server can handle? What's the output of "ps ax | grep diamond"?

**Comment by aj-jester** [comment]
@rtoma 

* the collectors are run every 10 seconds
* there are on average 10 collectors running per node

```

diamond  11226  0.0  0.2  77416 20648 ?        Ss   Jun03  16:43 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29589  0.2  0.3  84320 25628 ?        S    18:15   0:18 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29590  0.2  0.4  92376 33724 ?        S    18:15   0:18 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29591  0.2  0.4  94752 36120 ?        S    18:15   0:19 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29592  0.2  0.4  93052 34296 ?        S    18:15   0:18 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29593  0.2  0.3  81832 23032 ?        S    18:15   0:18 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29594  0.2  1.3 160716 101940 ?       S    18:15   0:21 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29595  0.2  0.2  80752 22096 ?        S    18:15   0:18 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
diamond  29596  0.2  0.8 124668 65832 ?        S    18:15   0:19 /usr/bin/python /usr/bin/diamond --foreground --skip-change-user --skip-fork --skip-pidfile
```

**Comment by aj-jester** [comment]
@rtoma @jgoldschrafe I set virtual memory (address space) ulimit to `512` MB and bumped the polling interval to `30` seconds and I no more see `Took too long to run! Killed!`.

I have 10 collectors running and setting the ulimit to `128` MB crashed diamond.

**Comment by Investocat** [comment]
@aj-jester virtual memory is 'free', it's not really useful to limit it. You should be limiting the max memory size instead and that should allow the collectors to work in a much smaller window.

**Comment by aj-jester** [comment]
@Investocat Ah gotcha. Which setting in ulimit would you recommend for this?

**Comment by Investocat** [comment]
max memory size, -m, should be the correct one.

**Comment by aj-jester** [comment]
@Investocat http://stackoverflow.com/questions/3360348/why-ulimit-cant-limit-resident-memory-successfully-and-how
