### ISSUE TITLE
dpkg --purge removes /lib/init/upstart-job

### ISSUE THREAD

**Issue by accuracy23** [python-diamond/Diamond#96]
As the title says, purging the diamond deb removes /lib/init/upstart-job. I had originally raised this in the Brightcove repo before realizing that this was active repo. I've just rebuilt a fresh deb package from this repository and the issue seems to still be present.

**Comment by JasonJanelle** [comment]
I can confirm that this is happening.

**Comment by deejay1** [comment]
Can you check if the package from the build from the PR fixes this issue?

**Comment by accuracy23** [comment]
Yes it works!

```
# ls -l /lib/init/upstart-job
-rwxr-xr-x 1 root root 3444 Jan 18  2013 /lib/init/upstart-job
# dpkg --purge diamond
(Reading database ... 68060 files and directories currently installed.)
Removing diamond ...
diamond stop/waiting
Purging configuration files for diamond ...
Processing triggers for python-support ...
Processing triggers for ureadahead ...
# ls -l /lib/init/upstart-job
-rwxr-xr-x 1 root root 3444 Jan 18  2013 /lib/init/upstart-job
```

**Comment by deejay1** [comment]
Great, I hope it gets merged soon ;)

**Comment by josegonzalez** [comment]
The pr was merged, thanks @deejay1 !
